const SUPABASE_URL = 'https://YOUR_PROJECT.supabase.co';
const SUPABASE_KEY = 'YOUR_PUBLISHABLE_KEY';
const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
const $ = id => document.getElementById(id);
const today = () => new Date().toISOString().slice(0, 10);
let signup = false;
function escapeHtml(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function emailFor(u){return `${u.toLowerCase().replace(/[^a-z0-9_]/g,'')}@lunar.local`}
window.showView=function(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===name));document.querySelectorAll('.nav button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));location.hash=name;if(name==='home'||name==='tasks')loadData()};
function taskCard(t,o){const done=o.status==='completed';return `<div class="task"><button class="check ${done?'done':''}" data-occ="${o.id}" aria-label="Complete"></button><div class="task-main"><div class="task-title">${escapeHtml(t.title)}</div><div class="task-meta">${o.scheduled_date} · ${t.priority}</div></div><span class="pill">${done?'Done':o.status}</span></div>`}
async function loadData(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:tasks=[]}=await supabase.from('lunar_tasks').select('*').order('created_at',{ascending:false});const {data:occ=[]}=await supabase.from('lunar_task_occurrences').select('*').eq('scheduled_date',today());const done=occ.filter(x=>x.status==='completed').length;$('stats').innerHTML=`<div class="card stat"><span class="muted">Today</span><b>${done}/${occ.length}</b><div class="progress"><i style="width:${occ.length?done/occ.length*100:0}%"></i></div></div><div class="card stat"><span class="muted">Plans</span><b>${tasks.filter(t=>t.status==='active').length}</b></div><div class="card stat"><span class="muted">Completion</span><b>${occ.length?Math.round(done/occ.length*100):0}%</b></div><div class="card stat"><span class="muted">Streak</span><b>—</b></div>`;$('todayCount').textContent=`${done}/${occ.length}`;$('todayTasks').innerHTML=occ.length?occ.map(o=>taskCard(tasks.find(t=>t.id===o.task_id)||{title:'Task',priority:'medium'},o)).join(''):`<div class="empty">Nothing scheduled today. Create something that matters.</div>`;$('allTasks').innerHTML=tasks.length?tasks.map(t=>`<div class="card" style="margin-bottom:10px"><div class="row"><div><b>${escapeHtml(t.title)}</b><div class="task-meta">${t.task_type} · ${t.priority}</div></div><span class="pill">${t.status}</span></div></div>`).join(''):`<div class="empty">Your plan is empty. Start with one useful action.</div>`;document.querySelectorAll('[data-occ]').forEach(b=>b.onclick=async()=>{await supabase.from('lunar_task_occurrences').update({status:'completed',completed_at:new Date().toISOString()}).eq('id',b.dataset.occ);loadData()})}
function occurrences(taskId,userId,start,end,repeat){const out=[];let d=new Date(start+'T00:00:00'),last=new Date(end+'T00:00:00'),first=d.getDay();while(d<=last){const day=d.getDay(),ok=repeat==='daily'||(repeat==='weekdays'&&day>0&&day<6)||(repeat==='weekly'&&day===first);if(ok)out.push({task_id:taskId,user_id:userId,scheduled_date:d.toISOString().slice(0,10),status:'upcoming'});d.setDate(d.getDate()+1)}return out}
$('authForm').onsubmit=async e=>{e.preventDefault();$('authError').textContent='';const u=$('username').value.trim().toLowerCase(),p=$('password').value;if(!/^[a-z0-9_]{3,24}$/.test(u)){ $('authError').textContent='Use 3–24 lowercase letters, numbers or underscores.';return}const r=signup?await supabase.auth.signUp({email:emailFor(u),password:p,options:{data:{username:u}}}):await supabase.auth.signInWithPassword({email:emailFor(u),password:p});if(r.error){$('authError').textContent=r.error.message;return}if(signup&&r.data.user)await supabase.from('lunar_profiles').upsert({id:r.data.user.id,username:u,display_name:u,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone});init()};
$('toggleAuth').onclick=()=>{signup=!signup;$('authTitle').textContent=signup?'Create your Lunar account.':'Welcome back.';$('authSubmit').textContent=signup?'Create account':'Sign in';$('toggleAuth').textContent=signup?'I already have an account':'Create account'};
$('taskForm').onsubmit=async e=>{e.preventDefault();const {data:{user}}=await supabase.auth.getUser();const start=$('start').value||today(),end=$('end').value||start,type=$('type').value;const {data:t,error}=await supabase.from('lunar_tasks').insert({user_id:user.id,title:$('title').value.trim(),description:$('description').value.trim()||null,task_type:type,priority:$('priority').value,start_date:start,end_date:end,recurrence_rule:type==='one_time'?null:{repeat:$('repeat').value}}).select().single();if(error){alert(error.message);return}let rows=type==='one_time'?[{task_id:t.id,user_id:user.id,scheduled_date:start,status:'upcoming'}]:occurrences(t.id,user.id,start,end,$('repeat').value);if(rows.length)await supabase.from('lunar_task_occurrences').insert(rows);e.target.reset();$('start').value=today();showView('home')};
$('evalForm').onsubmit=async e=>{e.preventDefault();const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('lunar_evaluations').upsert({user_id:user.id,evaluation_date:today(),mood:+$('mood').value,focus:+$('focus').value,energy:+$('energy').value,reflection:$('reflection').value});if(error)alert(error.message);else{$('reflection').value='';alert('Evaluation saved.')}};
$('logout').onclick=async()=>{await supabase.auth.signOut();location.reload()};
async function init(){const {data:{session}}=await supabase.auth.getSession();if(!session){$('auth').hidden=false;$('app').hidden=true;return}$('auth').hidden=true;$('app').hidden=false;const {data:p}=await supabase.from('lunar_profiles').select('username,created_at').eq('id',session.user.id).maybeSingle();$('profileName').textContent=p?.username||'Lunar user';$('profileSince').textContent=p?`Member since ${new Date(p.created_at).toLocaleDateString()}`:'';$('date').textContent=new Date().toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'});$('start').value=today();const h=location.hash.slice(1);if(['home','tasks','create','evaluate','profile'].includes(h))showView(h);loadData()}
document.querySelectorAll('.nav button[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});init();