import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const url='https://dpiwdhtbhwjgatvcfkcb.supabase.co';
const key=['sb_','publishable_','PSZnTEo74jObih_6TTpXVQ_tJwzTnXY'].join('');
const sb=createClient(url,key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});
let user=null,data={tasks:[],occ:[],subs:[],milestones:[],evals:[]},loaded=false,loadingPromise=null;
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const today=()=>new Date().toISOString().slice(0,10);
const style=document.createElement('style');style.textContent='@media(max-width:620px){.workspace-strip{grid-template-columns:1fr!important}.form-footer{flex-wrap:wrap}.form-footer .btn{flex:1;min-width:130px}}';document.head.appendChild(style);
function withTimeout(p,ms=7000){return Promise.race([p,new Promise((_,reject)=>setTimeout(()=>reject(new Error('timeout')),ms))]);}
async function syncExtras(){if(!user||!navigator.onLine)return;const k=`lunar-queue-${user.id}`,q=JSON.parse(localStorage.getItem(k)||'[]');if(!q.length)return;const rest=[];for(const op of q){try{if(op.type==='evaluation'){const r=await withTimeout(sb.from('lunar_evaluations').upsert(op.payload));if(r.error)throw r.error}else if(op.type==='settings'){const r=await withTimeout(sb.from('lunar_settings').upsert(op.payload));if(r.error)throw r.error}else rest.push(op)}catch{rest.push(op)}}localStorage.setItem(k,JSON.stringify(rest));}
async function get(force=false){if(loaded&&!force)return data;if(loadingPromise)return loadingPromise;loadingPromise=(async()=>{try{const r=await withTimeout(sb.auth.getUser(),5000);user=r.data?.user;if(!user)return data;await syncExtras();const [a,b,c,d,e]=await Promise.all([withTimeout(sb.from('lunar_tasks').select('*').order('created_at',{ascending:false}).limit(200)),withTimeout(sb.from('lunar_task_occurrences').select('*').order('scheduled_date',{ascending:false}).limit(1000)),withTimeout(sb.from('lunar_subtasks').select('*').limit(500)),withTimeout(sb.from('lunar_milestones').select('*').limit(500)),withTimeout(sb.from('lunar_evaluations').select('*').order('evaluation_date',{ascending:false}).limit(60))]);data.tasks=a.data||[];data.occ=b.data||[];data.subs=c.data||[];data.milestones=d.data||[];data.evals=e.data||[];loaded=true;inject();return data}catch(e){console.warn('Lunar enhancements deferred:',e);return data}finally{loadingPromise=null}})();return loadingPromise;}
function inject(){const home=$('home');if(home&&!$('workspaceStrip')){const x=document.createElement('div');x.id='workspaceStrip';x.className='grid workspace-strip';x.style.cssText='grid-template-columns:repeat(3,1fr);margin-top:14px';x.innerHTML=`<button class="card" style="text-align:left" data-jump="insights"><b>Insights</b><div class="hint">Patterns & consistency</div></button><button class="card" style="text-align:left" data-jump="calendar"><b>Calendar</b><div class="hint">See your month</div></button><button class="card" style="text-align:left" data-jump="history"><b>History</b><div class="hint">Your trail</div></button>`;const gp=$('goalPreview');gp?.parentNode?.appendChild(x);x.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>window.showView(b.dataset.jump));}
const p=$('profile');if(p&&!$('profileTools')){const card=document.createElement('div');card.id='profileTools';card.className='card';card.style.maxWidth='780px';card.innerHTML=`<div class="section-head" style="margin-top:0"><h3>Account tools</h3></div><div class="form-footer" style="justify-content:flex-start;flex-wrap:wrap"><button class="btn secondary" id="editProfile">Edit profile</button><button class="btn secondary" id="changePassword">Change password</button><button class="btn secondary" id="shareProgress">Share progress</button></div>`;p.appendChild(card);$('editProfile').onclick=editProfile;$('changePassword').onclick=changePassword;$('shareProgress').onclick=shareProgress;}renderAchievements();}
function renderAchievements(){const ins=$('insights');if(!ins||$('achievementCard'))return;const done=data.occ.filter(o=>o.status==='completed').length;const goals=data.tasks.filter(t=>t.task_type==='goal').length;const days=[...new Set(data.occ.filter(o=>o.status==='completed').map(o=>o.scheduled_date))].sort();let best=0,run=0,prev='';for(const d of days){if(prev&&((new Date(d)-new Date(prev))/86400000===1))run++;else run=1;best=Math.max(best,run);prev=d}const ach=[done>=1?'First step':null,done>=30?'Thirty done':null,best>=7?'One week strong':null,best>=30?'Month of consistency':null,goals>=1?'Goal setter':null].filter(Boolean);const c=document.createElement('div');c.id='achievementCard';c.className='card';c.style.marginTop='14px';c.innerHTML=`<div class="section-head" style="margin-top:0"><h3>Milestones earned</h3><span class="status">${ach.length}</span></div><div>${ach.length?ach.map(x=>`<span class="tag">${esc(x)}</span>`).join(''):'<span class="hint">Keep going. Your first milestone is close.</span>'}</div>`;ins.appendChild(c);}
async function editProfile(){await get();const r=await withTimeout(sb.from('lunar_profiles').select('display_name,username,timezone').eq('id',user.id).single());const p=r.data||{};window.__lunarEnhModal(`<div class="modal-head"><div><div class="eyebrow">Account</div><h2>Edit profile</h2></div><button class="modal-close" data-close>×</button></div><div class="form"><div class="field"><label>Display name</label><input id="epName" value="${esc(p.display_name||p.username||'')}"></div><div class="field"><label>Timezone</label><input id="epTz" value="${esc(p.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone)}"></div><button class="btn primary" id="epSave">Save profile</button></div>`);$('epSave').onclick=async()=>{const b=$('epSave');b.disabled=true;b.textContent='Saving…';const {error}=await withTimeout(sb.from('lunar_profiles').update({display_name:$('epName').value.trim(),timezone:$('epTz').value.trim()}).eq('id',user.id));if(error){b.disabled=false;b.textContent='Save profile';return alert('Could not save profile')}window.__lunarCloseModal();location.reload();};}
async function changePassword(){window.__lunarEnhModal(`<div class="modal-head"><div><div class="eyebrow">Security</div><h2>Change password</h2></div><button class="modal-close" data-close>×</button></div><div class="form"><div class="field"><label>New password</label><input id="newPass" type="password" minlength="8" placeholder="At least 8 characters"></div><button class="btn primary" id="passSave">Update password</button></div>`);$('passSave').onclick=async()=>{const p=$('newPass').value;if(p.length<8)return alert('Use at least 8 characters.');const b=$('passSave');b.disabled=true;b.textContent='Updating…';const {error}=await withTimeout(sb.auth.updateUser({password:p}));if(error){b.disabled=false;b.textContent='Update password';return alert(error.message)}window.__lunarCloseModal();alert('Password updated.');};}
async function shareProgress(){await get();const done=data.occ.filter(o=>o.status==='completed').length;const total=data.occ.filter(o=>o.scheduled_date<=today()).length;const text=`I’m building consistency with Lunar. ${done} actions completed, ${total?Math.round(done/total*100):0}% consistency.`;if(navigator.share){try{await navigator.share({title:'My Lunar progress',text})}catch{}}else{await navigator.clipboard?.writeText(text);alert('Progress copied.');}}
window.__lunarEnhModal=html=>{const b=$('modalBackdrop');$('modal').innerHTML=html;b.classList.remove('hidden');document.querySelectorAll('[data-close]').forEach(x=>x.onclick=window.__lunarCloseModal)};window.__lunarCloseModal=()=>{$('modalBackdrop')?.classList.add('hidden')};
new MutationObserver(()=>{const m=$('modal');if(!m||m.classList.contains('enhanced'))return;const h=m.querySelector('h2');if(!h)return;const t=data.tasks.find(x=>x.title===h.textContent.trim());if(!t)return;m.classList.add('enhanced');const box=document.createElement('div');box.className='form-footer';box.style.marginTop='14px';box.innerHTML=`<button class="btn secondary" id="logTime">Log time</button><button class="btn secondary" id="shareTask">Share</button>`;m.appendChild(box);$('logTime').onclick=async()=>{const n=Number(prompt('Minutes spent on this action?',String(t.estimated_minutes||30)));if(!n||n<1)return;const o=data.occ.filter(x=>x.task_id===t.id).find(x=>x.status==='completed')||data.occ.find(x=>x.task_id===t.id);if(!o)return alert('No occurrence found.');const {error}=await withTimeout(sb.from('lunar_task_occurrences').update({actual_minutes:n}).eq('id',o.id).eq('user_id',user.id));if(error)return alert('Could not log time.');alert('Time logged.');get(true)};$('shareTask').onclick=()=>navigator.share?navigator.share({title:t.title,text:`Working on ${t.title} with Lunar.`}):navigator.clipboard?.writeText(`Working on ${t.title} with Lunar.`);}).observe(document.body,{childList:true,subtree:true});
window.addEventListener('online',()=>{loaded=false;get(true)});
sb.auth.onAuthStateChange((e,s)=>{if(s&&!user){user=s.user;loaded=false;setTimeout(()=>get(true),300)}});
setTimeout(()=>{if(document.visibilityState==='visible')get()},1200);
